version: "3.7"

services:
  web:
    image: flask-test:latest
    build: .
    networks:
      - app-network
    ports:
      - "12345:12345"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DB=example

  db:
    image: mysql:latest
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "54321:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

networks:
  app-network:
    driver: overlay
