version: "3.7"

services:
  web:
    image: treepaech/flask-test
    build:
      context: ./app
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
    networks:
      - app-network
    ports:
      - "12345:12345"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DB=example

  db:
    image: treepaech/mysql-test
    build:
      context: ./mysql
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
    networks:
      - app-network
    ports:
      - "54321:3306"

networks:
  app-network:
    driver: overlay
